(()=>{
const c=window.FORESHADOW_COLLAB_CONFIG||{},root=document.getElementById('collab-notes'),badge=document.getElementById('collab-storage-badge'),form=document.getElementById('collab-add-form');if(!root||!form)return;
const readHeaders=()=>({'apikey':c.supabaseAnonKey,'Authorization':`Bearer ${c.supabaseAnonKey}`,'Content-Type':'application/json'}),base=`${c.supabaseUrl}/rest/v1`,fn=`${c.supabaseUrl}/functions/v1/foreshadow-collab`;
let notes=[],history=[],mode='open',paul=false,filtersOpen=false,statusFilter='all',priorityFilter='all',sceneFilter=null,searchFilter='',editorRole=null,editorCode=localStorage.getItem('foreshadow_editor_code')||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const reviewed=n=>!!n.reviewed_at,needsPaul=n=>!reviewed(n)&&n.author!=='Paul',hasNote=n=>!!String(n.response||'').trim(),unresolved=n=>!reviewed(n)||['unanswered','discussing'].includes(n.status);
const statusLabels={unanswered:'No decision recorded',discussing:'Keep thinking about it',agreed:'Useful / noted',rejected:'Not taking forward',rewrite:'May affect a rewrite'};
async function read(path){const r=await fetch(base+path,{headers:readHeaders()});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
async function write(payload,code=editorCode){const r=await fetch(fn,{method:'POST',headers:{'Content-Type':'application/json','x-foreshadow-code':code},body:JSON.stringify(payload)});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`Request failed (${r.status})`);return body}
async function identify(code=editorCode){if(!code)return null;try{const r=await write({action:'whoami'},code);editorRole=r.role||null;return editorRole}catch{editorRole=null;return null}}
async function unlock(expected){let code=editorCode;if(!code){code=prompt(`${expected||'Editor'} access code`,'')||'';if(!code)return false}let role=await identify(code);if(!role&&code===editorCode){localStorage.removeItem('foreshadow_editor_code');editorCode='';code=prompt(`${expected||'Editor'} access code`,'')||'';if(!code)return false;role=await identify(code)}if(!role){alert('That editor code was not recognised.');return false}if(expected&&role!==expected){alert(`This action needs ${expected}'s editor code.`);return false}editorCode=code;localStorage.setItem('foreshadow_editor_code',code);render();return true}
function lockEditor(){localStorage.removeItem('foreshadow_editor_code');editorCode='';editorRole=null;paul=false;document.body.classList.remove('paul-mode');render()}
function ensureAuditUI(){
  if(!document.getElementById('script-state')){const sec=document.createElement('section');sec.id='script-state';sec.className='section script-state';sec.innerHTML=`<div class="section-head"><div class="section-index">SCRIPT STATUS</div><div><div class="source-row"><span class="source-tag script">SCRIPT</span><span class="source-tag paul">PAUL</span></div><h2>What exists now, and what Paul plans to change.</h2><p class="section-intro">The site keeps the screenplay you read separate from changes Paul has said he intends to make.</p></div></div><div class="script-state-grid"><article><span class="source-tag script">CURRENT SCRIPT</span><h3>Opening currently on the page</h3><p>Adult Jay is introduced as a highly precise prop maker in a movie-prop workshop. The workplace conflict, disciplinary meeting and his decision to quit all belong to the current screenplay version.</p></article><article><span class="source-tag paul">PAUL — PLANNED CHANGE</span><h3>Opening rewrite</h3><p>Paul has said he is rewriting the opening and intends to make Jay a social worker. Until that rewrite appears in the screenplay, the reference sections below continue to describe the existing prop-maker version.</p></article></div><div class="source-legend"><span class="source-tag script">SCRIPT</span><span>established on the page</span><span class="source-tag chris">CHRIS</span><span>reader feedback</span><span class="source-tag paul">PAUL</span><span>Paul’s clarification or decision</span><span class="source-tag unresolved">UNRESOLVED</span><span>not yet answered or paid off</span></div>`;document.getElementById('start')?.after(sec)}
  ['navigator','reference','story','characters','timeline','threads','relationships','travel','investigation','locations','objects'].forEach(id=>{const h=document.querySelector(`#${id} .section-head>div:last-child`);if(h&&!h.querySelector('.source-tag.script'))h.insertAdjacentHTML('afterbegin','<span class="source-tag script section-source">SCRIPT</span>')})
  if(!document.querySelector('link[href="audit-fixes.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='audit-fixes.css?v=20260811-1';document.head.appendChild(l)}
}
async function load(){ensureAuditUI();notes=await read('/foreshadow_notes?select=*&order=created_at.asc');history=await read('/foreshadow_note_history?select=*&order=created_at.desc');await identify();window.FORESHADOW_NOTES=notes;render();decorateScenes();window.dispatchEvent(new CustomEvent('foreshadow-notes-loaded',{detail:{notes}}))}
function statusPill(n){if(!reviewed(n))return '<span class="source-tag unresolved">UNRESOLVED</span>';return `<span class="source-tag paul">PAUL</span><span class="decision-chip">${esc(statusLabels[n.status]||n.status)}</span>`}
function matches(n){if(paul)return needsPaul(n);if(mode==='open'&&reviewed(n))return false;if(mode==='reviewed'&&!reviewed(n))return false;if(statusFilter!=='all'&&n.status!==statusFilter)return false;if(priorityFilter!=='all'&&n.priority!==priorityFilter)return false;if(sceneFilter!==null&&n.scene_index!==sceneFilter)return false;if(searchFilter&&!`${n.title} ${n.note} ${n.response||''}`.toLowerCase().includes(searchFilter))return false;return true}
function renderTop(){let box=document.getElementById('feedback-simple-nav');if(paul){box?.remove();return}if(!box){box=document.createElement('div');box.id='feedback-simple-nav';box.className='feedback-simple-nav';root.before(box)}const open=notes.filter(n=>!reviewed(n)).length,done=notes.filter(reviewed).length;box.innerHTML=`<div class="feedback-tabs"><button class="feedback-tab ${mode==='open'?'active':''}" data-feedback-mode="open"><b>${open}</b> Open feedback</button><button class="feedback-tab ${mode==='reviewed'?'active':''}" data-feedback-mode="reviewed"><b>${done}</b> Reviewed</button></div><div class="feedback-tools-lite"><button id="toggle-more-filters" type="button">${filtersOpen?'Hide filters':'More filters'}</button><button id="editor-access" type="button">${editorRole?`${esc(editorRole)} editing · lock`:'Editor access'}</button></div>`}
function renderFilters(){let box=document.getElementById('collab-controls');if(paul||!filtersOpen){box?.remove();return}if(!box){box=document.createElement('div');box.id='collab-controls';box.className='collab-controls';root.before(box)}box.innerHTML=`<label class="control-search">Search feedback<input id="note-search" type="search" value="${esc(searchFilter)}" placeholder="Clark, time travel, Ade…"></label><label>Paul's position<select id="status-filter"><option value="all">All</option>${Object.entries(statusLabels).map(([v,l])=>`<option value="${v}" ${statusFilter===v?'selected':''}>${esc(l)}</option>`).join('')}</select></label><label>Importance<select id="priority-filter"><option value="all">All</option>${['Major','Medium','Minor'].map(v=>`<option value="${v}" ${priorityFilter===v?'selected':''}>${v}</option>`).join('')}</select></label><button id="clear-note-filters" type="button">Clear filters</button>${sceneFilter!==null?`<span class="active-scene-filter">Scene ${sceneFilter+1} only <button type="button" id="clear-scene-filter">×</button></span>`:''}`}
function renderPaulHead(){let h=document.getElementById('paul-inbox-head');if(!paul){h?.remove();return}if(!h){h=document.createElement('div');h.id='paul-inbox-head';h.className='paul-inbox-head';root.before(h)}const count=notes.filter(needsPaul).length;h.innerHTML=`<div><span class="source-tag paul">PAUL</span><h3>${count?`${count} feedback point${count===1?'':'s'} waiting for review`:'You’re caught up'}</h3><p>These are Chris’s reader notes. You do not need to explain the screenplay back to him. Mark what you want to do with each point; add a note only if it is useful.</p></div><button id="exit-paul-inbox" type="button">Back to full site</button>`}
function renderForm(){const add=document.querySelector('.collab-add');if(!add)return;if(paul||editorRole!=='Chris'){add.classList.add('is-locked');form.innerHTML=`<div class="editor-locked"><span class="source-tag chris">CHRIS</span><strong>${editorRole==='Paul'?'Paul cannot add Chris’s feedback.':'Chris editor access is required to add feedback.'}</strong>${editorRole?``:`<button type="button" id="unlock-chris">Unlock Chris editing</button>`}</div>`;return}add.classList.remove('is-locked');form.innerHTML=`<label>Type<select name="category"><option>Suggestion</option><option>Story clarity</option><option>Plot question</option><option>Niggle</option><option>Character</option><option>Time travel</option><option>Possible cut</option><option>Idea to consider</option></select></label><label>Importance<select name="priority"><option>Major</option><option selected>Medium</option><option>Minor</option></select></label><label>Attach to<select name="scope"><option value="whole">Whole screenplay</option><option value="scene">Specific scene</option></select></label><label class="wide">Heading<input name="title" required placeholder="What stood out?"></label><label class="wide">Reader note<textarea name="note" required placeholder="Question, observation or suggestion…"></textarea></label><label>Scene number (only if specific scene)<input name="scene" type="number" min="1" max="${(window.FORESHADOW?.beats||[]).length||99}"></label><button type="submit">Add feedback</button>`}
function cardHtml(n){const h=history.filter(z=>z.note_id===n.id);if(paul)return `<article class="collab-card paul-inbox-card ${n.priority==='Major'?'is-major':''}" data-id="${esc(n.id)}"><div class="collab-card-head"><div><div class="source-row"><span class="source-tag chris">CHRIS</span><span class="collab-category">${esc(n.category)}</span></div><h3>${esc(n.title)}</h3><div class="collab-meta"><span class="meta-chip priority-${esc(n.priority)}">${esc(n.priority)}</span>${n.scene_index!=null?`<button type="button" class="meta-chip scene-chip" data-open-scene="${n.scene_index}">Scene ${n.scene_index+1}</button>`:'<span class="meta-chip">Whole screenplay</span>'}</div></div></div><p class="collab-note">${esc(n.note)}</p><div class="paul-decision"><label>What do you want to do?<select class="collab-status"><option value="unanswered">No decision yet</option><option value="discussing">Keep thinking about it</option><option value="agreed">Useful / noted</option><option value="rejected">Not taking forward</option><option value="rewrite">May affect a rewrite</option></select></label><label>Optional note<textarea class="collab-response" rows="3" placeholder="Only add a note if it helps record your thinking…"></textarea></label></div><div class="collab-actions"><button class="collab-save" type="button">Mark reviewed</button><span class="collab-save-state"></span></div></article>`;
return `<article class="collab-card ${n.priority==='Major'?'is-major':''}" data-id="${esc(n.id)}"><div class="collab-card-head"><div><div class="source-row"><span class="source-tag chris">CHRIS</span><span class="collab-category">${esc(n.category)}</span>${!reviewed(n)?'<span class="source-tag unresolved">UNRESOLVED</span>':''}</div><h3>${esc(n.title)}</h3><div class="collab-meta"><span class="meta-chip priority-${esc(n.priority)}">${esc(n.priority)}</span>${n.scene_index!=null?`<button type="button" class="meta-chip scene-chip" data-open-scene="${n.scene_index}">Scene ${n.scene_index+1}</button>`:'<span class="meta-chip">Whole screenplay</span>'}</div></div><div class="card-state">${statusPill(n)}</div></div><p class="collab-note">${esc(n.note)}</p>${reviewed(n)?`<section class="paul-record"><div class="source-row"><span class="source-tag paul">PAUL</span><strong>${esc(statusLabels[n.status]||'Reviewed')}</strong></div>${hasNote(n)?`<p>${esc(n.response)}</p>`:'<p class="muted-note">No written note — Paul only recorded a decision.</p>'}</section>`:''}<div class="collab-actions">${editorRole==='Chris'?`<button class="collab-delete" type="button">Remove feedback</button>`:''}</div>${h.length?`<details class="history"><summary>History (${h.length})</summary>${h.map(z=>`<div class="history-entry"><strong>${esc(z.actor)}</strong> · ${esc(z.action)}<span>${new Date(z.created_at).toLocaleString()}</span></div>`).join('')}</details>`:''}</article>`}
function render(){renderTop();renderFilters();renderPaulHead();renderForm();const show=notes.filter(matches);root.innerHTML=show.map(cardHtml).join('')||(paul?'<div class="empty-workspace paul-empty"><strong>Nothing is waiting for Paul.</strong><span>All current reader feedback has been reviewed.</span><button id="exit-paul-empty" type="button">Back to full site</button></div>':'<div class="empty-workspace"><strong>No feedback in this view.</strong><span>Try the other tab or clear the filters.</span></div>')}
async function savePaul(card){const status=card.querySelector('.collab-status').value,response=card.querySelector('.collab-response').value,state=card.querySelector('.collab-save-state');state.textContent='Saving…';await write({action:'review_note',id:card.dataset.id,status,response});state.textContent='Saved';await load()}
function focusScene(i){closePaul(false);const row=document.querySelector(`[data-scene="${i+1}"]`);if(row){row.open=true;row.scrollIntoView({behavior:'smooth',block:'center'})}}
async function openPaul(){if(!(await unlock('Paul')))return;paul=true;mode='open';filtersOpen=false;document.body.classList.add('paul-mode');document.getElementById('collaboration')?.scrollIntoView({behavior:'smooth'});render()}
function closePaul(scroll=true){paul=false;document.body.classList.remove('paul-mode');render();if(scroll)document.getElementById('for-paul')?.scrollIntoView({behavior:'smooth',block:'start'})}
function decorateScenes(){document.querySelectorAll('.scene-row').forEach(row=>{const i=Number(row.dataset.scene)-1,related=notes.filter(n=>n.scene_index===i),body=row.querySelector('.scene-body'),summary=row.querySelector('summary');summary?.querySelector('.scene-notes-badge')?.remove();body?.querySelector('.scene-dev-actions')?.remove();if(related.length&&summary){const b=document.createElement('button');b.type='button';b.className='scene-notes-badge';b.dataset.sceneNotes=String(i);b.innerHTML=`${related.length} reader note${related.length===1?'':'s'}`;summary.appendChild(b)}if(body&&editorRole==='Chris'){const a=document.createElement('div');a.className='scene-dev-actions';a.innerHTML=`<button type="button" data-add-scene-note="${i}">Add reader feedback</button>${related.length?`<button type="button" data-scene-notes="${i}">View linked feedback</button>`:''}`;body.appendChild(a)}})}
root.addEventListener('click',async e=>{const scene=e.target.closest('[data-open-scene]');if(scene){focusScene(Number(scene.dataset.openScene));return}const card=e.target.closest('.collab-card');if(!card)return;try{if(e.target.closest('.collab-save'))await savePaul(card);if(e.target.closest('.collab-delete')){if(editorRole!=='Chris'&&!(await unlock('Chris')))return;if(confirm('Remove this reader feedback note?')){await write({action:'delete_note',id:card.dataset.id});await load()}}}catch(err){console.error(err);const s=card.querySelector('.collab-save-state');if(s)s.textContent=err.message||'Could not save'}});
document.addEventListener('click',async e=>{if(e.target.closest('#open-paul-inbox')){openPaul();return}if(e.target.closest('#exit-paul-inbox')||e.target.closest('#exit-paul-empty')){closePaul();return}if(e.target.closest('#toggle-more-filters')){filtersOpen=!filtersOpen;render();return}if(e.target.closest('#editor-access')){if(editorRole)lockEditor();else await unlock();return}if(e.target.closest('#unlock-chris')){await unlock('Chris');return}const tab=e.target.closest('[data-feedback-mode]');if(tab){mode=tab.dataset.feedbackMode;render();return}if(e.target.closest('#clear-note-filters')){statusFilter='all';priorityFilter='all';sceneFilter=null;searchFilter='';render();return}const s=e.target.closest('[data-scene-notes]');if(s){mode='open';filtersOpen=true;sceneFilter=Number(s.dataset.sceneNotes);document.getElementById('collaboration')?.scrollIntoView({behavior:'smooth'});render();return}const a=e.target.closest('[data-add-scene-note]');if(a){if(editorRole!=='Chris'&&!(await unlock('Chris')))return;document.getElementById('collaboration')?.scrollIntoView({behavior:'smooth'});render();setTimeout(()=>{const scope=form.querySelector('[name="scope"]'),scene=form.querySelector('[name="scene"]');if(scope)scope.value='scene';if(scene)scene.value=Number(a.dataset.addSceneNote)+1;form.querySelector('[name="title"]')?.focus()},100)}});
document.addEventListener('input',e=>{if(e.target.id==='note-search'){searchFilter=e.target.value.trim().toLowerCase();render()}});document.addEventListener('change',e=>{if(e.target.id==='status-filter'){statusFilter=e.target.value;render()}if(e.target.id==='priority-filter'){priorityFilter=e.target.value;render()}});
form.addEventListener('submit',async e=>{e.preventDefault();if(editorRole!=='Chris'&&!(await unlock('Chris')))return;const d=new FormData(form),scope=d.get('scope'),scene=scope==='scene'&&d.get('scene')?Number(d.get('scene'))-1:null,item={action:'create_note',id:`note-${Date.now()}`,category:d.get('category'),priority:d.get('priority'),title:String(d.get('title')).trim(),note:String(d.get('note')).trim(),scene_index:Number.isInteger(scene)?scene:null};if(!item.title||!item.note)return;try{await write(item);form.reset();mode='open';await load()}catch(err){console.error(err);alert(err.message||'The feedback could not be saved.')}});
badge.textContent='Public read · protected editing';badge.className='collab-storage-badge online';load().catch(err=>{console.error(err);badge.textContent='Online connection failed';badge.className='collab-storage-badge local'});
})();