window.FORESHADOW = {
  summary: "In 1979, ten-year-old Clark Apsley disappears after Jay Cadell fails to meet him at the park. Decades later, Jay is still carrying the guilt. His adult life is collapsing when a school reunion brings him back to Canningford and reunites him with Susy Whitlock and Adrian 'Ade' Laurier. Ade has spent years circling the mystery of Clark, other missing children and powerful local men. He also possesses Pavahuasca, an Amazonian plant medicine that sends him and Jay back into their own ten-year-old bodies. Their attempts to investigate and change 1979 collide with a present-day surveillance operation, buried police evidence, Bartholomew's network and events that someone has been watching for thirty years.",

  beats: [
    { title: "1979 — Clark waits", text: "Jay tells Clark he will meet him later at the play park. Jay instead spends time with Susy. Clark waits alone, vanishes, and his old sixpence is left behind." },
    { title: "Adult Jay at work", text: "Jay Cadell is introduced as an exceptionally precise prop maker in a movie-prop workshop. His orderliness and OCD are immediately visible, as are the bullying and humiliation he faces from co-workers." },
    { title: "Jay walks out", text: "A disciplinary meeting over a workplace dispute becomes the final straw. Jay quits, loses access to the company vehicle and leaves with his belongings in a box." },
    { title: "Sally leaves", text: "Jay returns home to find Sally packed and ready to leave. She tells him he is getting worse, needs help and refuses to open up about whatever is driving him." },
    { title: "The hidden scrapbook", text: "A school-reunion post sends Jay back through old photographs. He retrieves a hidden scrapbook containing Clark's missing-child flyers, newspaper cuttings and the tarnished sixpence." },
    { title: "Violence and a rescuer", text: "Drunk and distraught, Jay is attacked by the men from work. A highly capable vagrant-like stranger intervenes, carries Jay away and is followed at a distance by a black car." },
    { title: "Return to Canningford", text: "Jay travels back to his childhood town for the reunion. Before the event he revisits the brook and other childhood territory, where present-day actions dissolve into memories of the gang as children." },
    { title: "The reunion", text: "At Canningford School Jay reconnects with Susy. Ade appears outside, thin, scruffy and carrying a battered camcorder. The old friendship briefly comes back to life." },
    { title: "Clark becomes an investigation", text: "Ade tells Jay and Susy that Clark was not the only missing child. He raises Lionel Bartholomew, powerful local connections and his belief that the original investigation was compromised." },
    { title: "The old friends remember", text: "Ade films Jay and Susy describing childhood memories: the brook, dens, fishing, Ade's brother, the Kangerellipigs story and the period before Clark vanished. The warmth of those memories contrasts with how completely Clark's disappearance broke the group." },
    { title: "Ade's life since school", text: "Ade describes seventeen years in the Royal Marines, tours in Afghanistan and Iraq, psychological damage, difficulty with authority and the isolated life he now leads." },
    { title: "Pavahuasca", text: "Ade gives Jay an infusion he calls Pavahuasca. Jay experiences intense physical effects and abruptly finds himself back at the brook in his ten-year-old body, with Ade beside him." },
    { title: "1979 is physically accessible", text: "Ade explains that they have time travelled, not hallucinated. Their adult awareness occupies their younger bodies, and the first objective is direct: stop Clark being abducted." },
    { title: "Ade's Amazon story", text: "Ade explains how he encountered the Hiding People after becoming lost and poisoned in the rainforest while attempting to reach an Ayahuasca retreat. They treated him, later gave him Pavahuasca and discovered that focusing on a remembered time could send him back to it." },
    { title: "Testing the past", text: "Jay and Ade use actions in 1979 to prove to themselves that the journey is real, including the hidden cigar tube. They visit Clark and see details neither adult remembered clearly." },
    { title: "Clark's possible future", text: "Clark reveals extraordinary skill with magic and sleight of hand. Jay and Ade realise the child they remember primarily as a victim might have grown into a gifted magician." },
    { title: "Bartholomew at Clark's house", text: "A black Bentley arrives at the Apsley home. Clark's father greets Bartholomew and Armstrong. Jay and Ade recognise the men as significant and begin connecting Clark's home life to the wider mystery." },
    { title: "Surveillance closes in", text: "A covert team in vehicles and monitoring rooms tracks Jay and Ade. They hold extensive files on both men, including Ade's military history and material hidden behind top-secret access." },
    { title: "Jay's flat has been entered", text: "Back in the present, Jay notices objects shifted in ways his OCD would not allow, drawers left wrong and his laptop history altered. He realises somebody has been inside." },
    { title: "A second violent 1979 encounter", text: "During another trip, Jay and Ade become caught in a dangerous incident at Bartholomew's property involving other children who fight their way out with startling skill. A black van awaits them nearby." },
    { title: "Susy follows the old police trail", text: "Using her investigative background, Susy speaks with retired officers Albert McGregor and Jean Logan. They describe historic evidence, unlawful phone taps, a cover-up and senior pressure that shut the investigation down." },
    { title: "The Bartholomew network", text: "Jean identifies Morris Fournier, Harold Louw and Jaqueline Lombard among people tied to the old case and recalls Bartholomew ordering those involved to maintain a burglary story after the attack." },
    { title: "The UV message", text: "Someone enters Ade's room without being seen and leaves information written in UV. The message contains map coordinates, the year 2012 and what appears to be another address." },
    { title: "Alang", text: "Jay and Ade use Google Earth to follow the coordinates to Alang on the north-west coast of India, where the imagery reveals evidence that something substantial had previously occupied the location." },
    { title: "Theory enters the classroom", text: "Back in 1979, young Jay and Ade discuss time travel with Miss Bancroft and their classmates, including the butterfly effect and the Novikov Self-Consistency Principle, while the adults' knowledge inside child bodies becomes increasingly conspicuous." },
    { title: "Clark is approached", text: "At the school gates Jay and Ade see Clark talking to the same suspicious adults. They deliberately memorise identifying details, including a vehicle registration and a distinctive facial mole." },
    { title: "Susy is attacked", text: "The present-day investigation turns openly dangerous when Susy is critically injured in a hit-and-run. Jay and Ade sit beside her in hospital as the cost of continuing becomes immediate." },
    { title: "Ade's buried trauma", text: "In the hospital, Ade finally reveals that after Clark vanished he went to Clark's house and was sexually abused by Clark's father, Bartholomew and others. The revelation reframes his anger, obsession and refusal to walk away." },
    { title: "Shades confronts Jay", text: "A man known as Shades tells Jay that his organisation has watched Jay and Ade for thirty years. The organisation saw Ade, as a child, violently defeat adults and noticed that neither man spoke about it for decades before suddenly discussing it again." },
    { title: "The story remains in motion", text: "The screenplay reaches its late stage with Susy hospitalised, Jay and Ade exposed to a long-running surveillance organisation and their efforts in 1979 now clearly connected to events other people have been tracking since childhood." }
  ],

  characters: [
    { name: "Jay Cadell", role: "Central character", notes: "Early forties in the present. A gifted prop maker and engineer, intensely precise and highly organised, with OCD explicitly noted in the screenplay. Clark's disappearance has shaped his adult life. He is bullied at work, quits, loses Sally, returns to Canningford and becomes Ade's partner in travelling back to 1979." },
    { name: "Adrian 'Ade' Laurier", role: "Central character", notes: "Jay's childhood friend. Former Royal Marine with combat experience in Afghanistan and Iraq, later traumatised and socially isolated. He discovered Pavahuasca through the Hiding People, has travelled into his younger self before the story begins and has been investigating Clark and Bartholomew. His own abuse by the men around Clark's father is revealed late in the script." },
    { name: "Clark Apsley", role: "Missing child", notes: "Jay and Ade's childhood friend, around ten in 1979. Dark-haired, smaller than Jay and unusually talented at magic and sleight of hand. His sixpence is found after he vanishes. Preventing his disappearance is the central reason Jay and Ade return to 1979." },
    { name: "Susy Whitlock", role: "Childhood friend / investigator", notes: "Jay and Ade's lifelong friend. She uses a wheelchair, organises the reunion, is a former police intelligence officer and now owns Susy's Flowers. She becomes an active investigator of the old police case and later suffers a severe hit-and-run attack." },
    { name: "Sally", role: "Jay's partner at the opening", notes: "Leaves Jay shortly after he quits his job. She tells him he is worsening, needs help and has repeatedly failed to let her understand what is happening inside him." },
    { name: "Lionel Bartholomew", role: "Primary figure in the historic case", notes: "A local-government figure in 1979 who later becomes a judge. He visits Clark's father, is linked by Ade and retired police to child sexual exploitation and a historic cover-up, and is named by Ade as one of his abusers." },
    { name: "Mr. Apsley", role: "Clark's father", notes: "Clark's father. Receives Bartholomew and Armstrong at the house and is later named by Ade as part of the group that abused him after Clark disappeared." },
    { name: "Mr. Armstrong", role: "Bartholomew associate", notes: "Arrives at Clark's house with Bartholomew in a black Bentley. Jay recognises him as Gary Armstrong's father." },
    { name: "Shades", role: "Surveillance organisation", notes: "A senior figure in the covert organisation watching Jay and Ade. He has access to deep personal and classified information and tells Jay the organisation has monitored the pair for roughly thirty years." },
    { name: "Mark Turner", role: "School friend", notes: "An old school friend who joins Jay, Ade and Susy at the reunion and helps flesh out the social world of their childhood." },
    { name: "Greg", role: "Barman / acquaintance", notes: "Works at the rough live-music bar Jay visits after Sally leaves. He tells Jay plainly that he has changed and may need help." },
    { name: "Lee", role: "Workshop foreman", notes: "Jay's foreman at the prop workshop. He calls Jay into the disciplinary meeting that leads to Jay walking away from the job." },
    { name: "Michael", role: "Workshop colleague", notes: "A source of conflict at Jay's workplace. Jay accuses him of adding unnecessary work to impress a director." },
    { name: "Albert McGregor", role: "Retired police source", notes: "A former officer Susy visits while reconstructing the 1979 case. He remembers missing evidence, senior interference and directs Susy to Jean Logan." },
    { name: "Jean Logan", role: "Retired police source", notes: "Former officer directly involved with the Bartholomew case. She remembers the injured adults, the covertly tapped hospital calls and the pressure that buried the case." },
    { name: "Morris Fournier", role: "Named historic associate", notes: "Named by Jean Logan as one of the people connected to the old case and later powerful in local government." },
    { name: "Harold Louw", role: "Named historic associate", notes: "Named by Jean Logan as another person tied to the old case and later established in local government." },
    { name: "Jaqueline Lombard", role: "Named historic associate", notes: "Named by Jean Logan as part of the historic case; she says Lombard later became a judge." },
    { name: "Miss Bancroft", role: "1979 teacher", notes: "Teacher confronted by ten-year-old Jay and Ade speaking with adult-level knowledge about time-travel theory. She assumes the boys are playing an elaborate game." },
    { name: "Andy Laurier", role: "Ade's older brother", notes: "Ade's older brother, remembered as charismatic and an excellent storyteller. His Kangerellipigs story is one of the group's strongest shared childhood memories." },
    { name: "The older boy and girl", role: "Unknown child operatives", notes: "Children encountered during the Bartholomew-house incident who fight adults with extraordinary skill and move toward a waiting black van. Their affiliation is not explained in the script section, but Jay and Ade recognise that they are not ordinary children." }
  ],

  timeline: [
    { label: "1979", title: "The original disappearance", text: "Jay misses the arranged meeting. Clark vanishes. Missing-child posters appear and Jay keeps Clark's sixpence." },
    { label: "Years later", title: "The group fractures", text: "Jay, Ade and Susy grow up carrying the effects of Clark's disappearance. Ade later says the event 'sucked all the colour' from their childhood." },
    { label: "Ade's adulthood", title: "Military service", text: "Ade serves seventeen years in the Royal Marines, including Afghanistan and Iraq, before leaving with serious psychological difficulties." },
    { label: "Ade's adulthood", title: "The rainforest", text: "Attempting to reach an Ayahuasca retreat, Ade ends up lost in the rainforest, poisoned by Lonomia caterpillars and rescued by the Hiding People." },
    { label: "Before reunion", title: "Ade discovers Pavahuasca", text: "The Hiding People treat Ade and later give him Pavahuasca while focusing him on happier memories. He experiences his first return to childhood and subsequently tests the phenomenon." },
    { label: "Present", title: "Jay's job ends", text: "Workplace bullying, conflict and disciplinary pressure culminate in Jay quitting the prop workshop." },
    { label: "Present", title: "Sally leaves", text: "Jay comes home to find Sally moving out and taking the cat, leaving him isolated." },
    { label: "Present", title: "Reunion invitation", text: "Jay finds the Canningford school reunion online, uncovers the Clark scrapbook and chooses to attend." },
    { label: "Present", title: "Canningford reunion", text: "Jay reunites with Susy and Ade. Ade introduces the wider missing-child pattern and Bartholomew." },
    { label: "Present → 1979", title: "Jay's first shown trip", text: "Jay drinks Pavahuasca with Ade and wakes in his ten-year-old body at the brook." },
    { label: "1979", title: "Testing reality", text: "Jay and Ade hide physical evidence, visit familiar places and establish that their actions occur inside the real 1979 environment they remember." },
    { label: "1979", title: "Clark before disappearance", text: "They spend time with Clark, discover his remarkable magic ability and see Bartholomew and Armstrong arrive at his house." },
    { label: "Present", title: "Surveillance becomes visible", text: "Black vehicles, covert monitoring and detailed personal files reveal that another organisation is already following their actions." },
    { label: "1979", title: "Bartholomew-house incident", text: "A later journey pulls Jay and Ade into a violent escape involving other highly trained children and a waiting black van." },
    { label: "Present", title: "Susy reconstructs the case", text: "Susy interviews Albert and Jean, recovering evidence of an old cover-up and names tied to Bartholomew." },
    { label: "Present", title: "The UV clue", text: "Hidden UV writing appears inside Ade's room and points them toward coordinates, 2012 and another address." },
    { label: "Present", title: "Alang lead", text: "The coordinates take them through historic satellite imagery to Alang in India." },
    { label: "1979", title: "School and Clark watched", text: "Jay and Ade openly discuss time-travel theory in class, then see Clark with suspicious adults outside school and memorise identifying details." },
    { label: "Present", title: "Susy nearly killed", text: "A hit-and-run leaves Susy critically injured and brings the investigation's danger directly into the group." },
    { label: "Present", title: "Ade's disclosure", text: "At the hospital Ade reveals the abuse he suffered immediately after Clark disappeared." },
    { label: "Present", title: "Thirty years of observation", text: "Shades tells Jay that the covert organisation has watched him and Ade since their childhood and noticed the impossible discontinuity in what they remembered and discussed." }
  ],

  travel: [
    { title: "Pavahuasca is the trigger", text: "The travel shown begins after drinking an infusion Ade calls Pavahuasca." },
    { title: "Memory selects the destination", text: "Ade says the Hiding People made him focus on happier memories before administering the infusion; he then returned to the childhood period he was remembering." },
    { title: "A 2:39 administration ritual", text: "Ade says the Hiding People sing while the infusion is administered and that the song lasts two minutes and thirty-nine seconds, which he describes as the optimum time for Pavahuasca to work." },
    { title: "Travellers inhabit younger bodies", text: "Jay and Ade do not arrive as adult bodies. Their adult awareness appears inside their ten-year-old selves." },
    { title: "Both travellers share the same past", text: "Ade uses the fact that he and Jay experience the same events as evidence that Jay is not simply hallucinating." },
    { title: "The body reacts", text: "Jay experiences rapid blinking, shallow breathing, visual distortion, severe nausea and repeated vomiting. Ade is physically affected but is more accustomed to it." },
    { title: "Trips have limited duration", text: "Ade can recognise when they are close to slipping back to the present, and return occurs without another dose being visibly taken." },
    { title: "Actions can be tested", text: "Jay and Ade deliberately leave or hide things in 1979, such as the cigar tube, to test whether the past they experience has physical continuity." },
    { title: "Adult knowledge remains available", text: "While in child bodies they retain adult vocabulary, memories, military experience and knowledge of later culture, sometimes exposing the mismatch to people in 1979." },
    { title: "The screenplay discusses causality", text: "In class Jay raises the butterfly effect and Ade cites the Novikov Self-Consistency Principle as a possible model for how changes to the past might remain coherent." },
    { title: "The script does not fully settle the model", text: "Characters debate how the mechanism works, but the screenplay presents the theories as discussion rather than a final scientific explanation." }
  ],

  investigation: [
    { title: "Eleven other missing children", text: "Ade tells Jay and Susy that eleven other children disappeared around the same period as Clark." },
    { title: "Bartholomew's status", text: "Ade identifies Bartholomew as a former town councillor who later becomes a High Court judge and says allegations involving minors repeatedly failed to stick." },
    { title: "Clark's home connection", text: "Jay and Ade see Bartholomew and Armstrong visiting Clark's father in 1979, strengthening the connection between the suspected network and Clark's immediate family." },
    { title: "Missing police evidence", text: "Albert remembers physical evidence and witness material disappearing, including a knife and a trophy, after the case was shut down from above." },
    { title: "Hospital phone taps", text: "Jean recalls that police secretly listened to the injured adults discussing the attack and Bartholomew ordering everyone to maintain the burglary story." },
    { title: "Senior obstruction", text: "Albert and Jean both describe the case being stopped despite their belief that something serious had happened. Albert identifies former DCI Mike Nielson as acting under orders from higher up." },
    { title: "Covert surveillance", text: "A separate modern organisation follows Jay and Ade, operates black vehicles and monitoring rooms and possesses exceptionally detailed files on them." },
    { title: "Ade's military file", text: "The surveillance team sees Ade's Royal Marine and SAS-related history, commendations, discharge information and a top-secret file they cannot initially access." },
    { title: "Thirty-year anomaly", text: "Shades says the organisation witnessed Ade's extraordinary childhood violence yet Jay and Ade did not speak about it for decades; their sudden present-day discussion is what makes the situation suspicious." },
    { title: "Unknown helpers / operatives", text: "The children encountered during the Bartholomew-house escape show unusual combat capability and move toward a black van, suggesting another organised presence around the 1979 events." }
  ],

  network: [
    ["Lionel Bartholomew", "Former local councillor; later judge; linked to Clark's father, historic abuse allegations, the covered-up house incident and Ade's personal trauma."],
    ["Mr. Apsley", "Clark's father; receives Bartholomew and Armstrong and is named in Ade's hospital disclosure."],
    ["Armstrong", "Visitor to the Apsley house; identified by Jay as Gary Armstrong's father."],
    ["Morris Fournier", "Named by Jean Logan among people connected to the historic case."],
    ["Harold Louw", "Named by Jean Logan among people connected to the historic case."],
    ["Jaqueline Lombard", "Named by Jean Logan; later a judge."],
    ["Mike Nielson", "Former DCI whom Albert says shut the investigation down under pressure from higher up."],
    ["Shades' organisation", "A separate covert structure with long-term surveillance capacity, black vehicles, deep databases and interest in the impossible timeline around Jay and Ade."]
  ],

  locations: [
    ["The play park", "Where the story opens in 1979, where Jay was meant to meet Clark and where Clark's sixpence remains after the disappearance."],
    ["Movie-prop workshop", "Jay's present-day workplace. It establishes his skill, obsessive precision, workplace bullying and the collapse that sends him out of his old routine."],
    ["Jay's flat", "Sally leaves here; Jay keeps the Clark scrapbook here; later he detects a covert entry because objects have been moved out of his exact order."],
    ["The rough live-music bar", "Jay drinks after Sally leaves, argues with Greg and later walks into the street where he is attacked by his former co-workers."],
    ["Canningford", "Jay, Ade, Susy and Clark's childhood town and the physical centre of both the 1979 and present-day mystery."],
    ["The brook", "A defining childhood place of fishing, dams, weed, dens and games. It is also the setting of Jay's first shown Pavahuasca journey."],
    ["Canningford School", "Site of the adult reunion and, in 1979, scenes where young Jay and Ade interact with Miss Bancroft and later observe Clark with suspicious adults."],
    ["Clark's house", "Where Jay and Ade see Clark's magic, meet the domestic environment around him and witness Bartholomew and Armstrong arrive."],
    ["Bartholomew's mansion / Grange", "The property linked to the historic police case, the violent child escape and the abuse network described later in the screenplay."],
    ["Ade's building / room", "Ade's current home in a rough communal building. It becomes a base for Jay and Ade and later the site of the unexplained UV message."],
    ["Susy's Flowers", "Susy's post-police life is built around her florist business, reinforcing how far her adult routine initially appears from the old case."],
    ["Primi's Italian Restaurant", "A present-day social location where Jay, Ade and Susy continue reconnecting while surveillance of them continues."],
    ["Albert McGregor's home", "One of Susy's stops while reconstructing the buried police investigation."],
    ["Jean Logan's bungalow", "Where Susy hears the most detailed surviving account of the Bartholomew-house case and the police cover-up."],
    ["Alang, India", "Location reached through coordinates hidden in Ade's room and examined through historic Google Earth imagery."],
    ["Hospital", "Where Susy lies critically injured, Ade reveals his childhood abuse and Jay is later questioned by Shades."]
  ],

  objects: [
    { title: "Clark's sixpence", text: "Clark rolls the coin over his fingers as a child. It is found after his disappearance and adult Jay keeps a tarnished sixpence with the old case material." },
    { title: "Missing-child posters", text: "Clark's disappearance is repeatedly represented by HAVE YOU SEEN CLARK APSLEY? flyers and other missing-child imagery." },
    { title: "Jay's scrapbook", text: "Hidden in a shoebox at the back of Jay's wardrobe. It contains missing-child flyers, newspaper reports and the sixpence." },
    { title: "School reunion photographs", text: "Photos reconnect Jay with the childhood group and visually expose Clark's absence from later life." },
    { title: "Ade's battered camcorder", text: "Ade films Jay and Susy recounting childhood memories at the reunion. Later, a camera is deliberately recovered during the Bartholomew-house escape." },
    { title: "Pavahuasca", text: "The plant infusion Ade receives through the Hiding People and later prepares for Jay. It is the screenplay's direct means of entering the past." },
    { title: "The Hiding People's chant", text: "A two-minute-thirty-nine-second ritual element Ade says accompanies administration of Pavahuasca." },
    { title: "The cigar tube", text: "A small aluminium cigar tube from Ade's father's cigars becomes a deliberate physical test left in the past." },
    { title: "Clark's cards and magic props", text: "Clark's sleight of hand with playing cards and improvised tricks reveals a talent his friends had never fully remembered." },
    { title: "Black Bentley", text: "The car in which Bartholomew and Armstrong arrive at Clark's house, marking their presence in Clark's domestic world." },
    { title: "Black surveillance vehicles", text: "Black car and vans recur around Jay, Ade and the unknown child operatives, tying the story to organised observation." },
    { title: "Surveillance files", text: "The modern organisation holds extremely detailed profiles on Jay and Ade, including military and classified information." },
    { title: "Jay's laptop history", text: "Its changed browser history helps Jay prove to himself that somebody has entered his flat and used or moved his computer." },
    { title: "Old police evidence", text: "Albert recalls a knife, a trophy, witness statements and other material disappearing when the Bartholomew case was suppressed." },
    { title: "UV writing", text: "A professional-looking message appears inside Ade's room in ultraviolet, containing coordinates, 2012 and another location clue." },
    { title: "Google Earth imagery", text: "Jay and Ade use historic satellite views to trace the UV coordinates to Alang and examine what used to be there." },
    { title: "Vehicle registration", text: "In 1979 Jay deliberately memorises the registration of a vehicle connected to adults speaking with Clark." },
    { title: "Distinctive facial mole", text: "Jay notices a woman's mole near her eye as another detail that can survive memory and help identify people later." }
  ]
};